export const items = [
  { id: 1, name: " Money Plant Golden", price: 250, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
  { id: 2, name: "Dracaena Golden Plant", price: 300, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 3, name: "Syngonium Pink Plant", price: 130, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 4, name: "Chocolate Queen Plant", price: 20, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 5, name: "Aralia Golden Plant", price: 190, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 6, name: "Peperomia Green Plant", price: 70, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 7, name: "Peperomia Creeper Plant", price: 30, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 8, name: "Boxwood Buxus Plant", price: 200, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 9, name: "Philodendron Xanadu plant", price: 100, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 10, name: "Golden Ferns", price:560, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  { id: 11, name: "Spider Plant", price: 900, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },


]