export const items = [
    { id: 1, name: "KN95 Mask", price: 250, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
    { id: 2, name: "Surgical Gloves", price: 300, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 3, name: "Walking Crutches", price: 130, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 4, name: "Blood Pressure Monitor", price: 20, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 5, name: "Dental Chair", price: 190, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 6, name: "Hygenic Tools", price: 70, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 7, name: "Pen Knife", price: 30, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 8, name: "Thermometer", price: 200, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 9, name: "Microscope", price: 100, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 10, name: "First Aid Kit", price:560, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 11, name: "Artery Forceps", price: 900, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  
  
  ]