export const items = [
    { id: 1, name: "Money Plant Variegated", price: 250, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') } ], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 50, rating: 4.5, category: 'male' },
    { id: 2, name: "Crassula Green Mini Plant", price: 300, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 3, name: "Chlorophytum Spider Plant", price: 130, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 4, name: "Christmas Cactus Plant", price: 20, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 5, name: "Aglaonema Red Plant", price: 190, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 6, name: "Dracaena Golden Milky", price: 70, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 7, name: "Areca Palm Plant", price: 30, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 8, name: "Syngonium Pink Neon", price: 200, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 9, name: "Sansevieria Golden", price: 100, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 10, name: "Golden Ferns", price:560, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
    { id: 11, name: "Spider Plant", price: 900, imgPath: require('../../assets/main.jpg'), gallery: [{ id: 1, imgPath: require('../../assets/main.jpg') }, { id: 2, imgPath: require('../../assets/main.jpg') }, { id: 3, imgPath: require('../../assets/main.jpg') }], desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dapibus diam sed bibendum accumsan. Vivamus ligula lorem, commodo nec pretium vel, consequat sit amet massa. Aliquam erat volutpat.', sold: 40, rating: 4.8, category: 'male' },
  
  
  ]